### PR TITLE
Generate fixed filenames for all types of files

### LINKED ISSUE #773: `--generate-exact` doesn't produce predictable header filenames
## Expected Behavior

According to the `gen --help`, using `--generate-exact` is supposed to produce easily predictable output filenames. This would be helpful for #478.

## Actual Behavior

The `.cc` files have predictable names, but the `.h` ones don't. They depend on the `include_cpp!` module names. This means my Bazel rule has to know all of the module names ahead of time to predict the `.h` filenames, which is a minor annoyance.

Having an option to name the `.h` files the same as their corresponding `.cc` files would be nice.

## Specifications

- Version: 0.16.0

### PR DESCRIPTION
**Pull request by bsilver8192**
Also update the documentation about how running `gen` with fixed
filenames works.

Fixes #773

### CODE REVIEW

**Comment by bsilver8192** [comment]
Given that the coverage of these tests still isn't too great, I also tested with my full use case before opening this PR. I think everything still compiles, but there's some unrelated new issues to chase down first.

File: demo/src/main.rs [hunk 1]
```diff
@@ -21,6 +21,9 @@ include_cpp! {
     generate!("Goat")
 }
 
+#[link(name = "autocxx-demo")]
+extern "C" {}
+
```
Comment (adetaylor) [inline demo/src/main.rs:26]: Why this change?

Comment (bsilver8192) [reply demo/src/main.rs:26]: That's how the .rs files generated by integration-tests get the static library linked in, and it seemed like a reasonable thing to add for a complete demo that can be built either way the docs mention.

Comment (adetaylor) [reply demo/src/main.rs:26]: Ah right, so this is on the basis that the demo code should build using `autocxx-gen` as well as `autocxx-build`?

I'd prefer to keep the demo code as simple as possible for the Cargo (`autocxx-build`) world, where this is already taken care of by the `build.rs`. I think anyone deviating from Cargo knows that they will need to jump through some hoops, and if they're using blaze/bazel/gn or similar, this `link` directive probably won't do the trick anyway.

File: engine/src/conversion/codegen_cpp/mod.rs [hunk 2]
```diff
@@ -235,7 +235,8 @@ impl<'a> CppCodeGenerator<'a> {
                 headers, self.inclusions, type_definitions, declarations
             );
             log::info!("Additional C++ decls:\n{}", declarations);
-            let header_name = format!("autocxxgen_{}.h", self.config.get_mod_name());
+            let header_name =
+                self.cpp_codegen_options.header_namer.0(self.config.get_mod_name().to_string());
```
Comment (adetaylor) [inline engine/src/conversion/codegen_cpp/mod.rs:239]: Nit: Would you mind adding an `impl` block so we can call a function `.name_header(..)` instead of `.0(..)`

File: gen/cmd/src/main.rs [hunk 3]
```diff
@@ -205,12 +213,26 @@ fn main() {
         .unwrap_or_default()
         .collect();
     let suppress_system_headers = matches.is_present("suppress-system-headers");
+    let desired_number = matches
+        .value_of("generate-exact")
+        .map(|s| s.parse::<usize>().unwrap());
+    let header_counter = Cell::new(0);
```
Comment (adetaylor) [inline gen/cmd/src/main.rs:219]: Nit: you could move this inside the 'if' block

**Comment by adetaylor** [comment]
This looks good - sorry I didn't get to it till now. Just a few nits.

File: demo/src/main.rs (hunk 1 above)
Comment (bsilver8192) [reply demo/src/main.rs:26]: Yes, exactly.

In that case, any thoughts on adding something for `autocxx-gen` tests to build? Could copy the whole directory, but that seems annoying.

Also, I'll back the tests out of this PR for now in the interests of getting the functional change merged.

File: engine/src/conversion/codegen_cpp/mod.rs (hunk 2 above)
Comment (bsilver8192) [reply engine/src/conversion/codegen_cpp/mod.rs:239]: Done

File: gen/cmd/src/main.rs (hunk 3 above)
Comment (bsilver8192) [reply gen/cmd/src/main.rs:219]: I don't think so? It needs to be scoped outside that so it can be used later.

Comment (adetaylor) [reply gen/cmd/src/main.rs:219]: Ah yeah.

File: demo/src/main.rs (hunk 1 above)
Comment (adetaylor) [reply demo/src/main.rs]: Ah right, it's used by the test code, that's the bit I hadn't realized.

Yeah - I'd still strongly prefer to avoid adding these lines into the demo. I want that to be focused on the simplest possible experience for cargo users. I'd be OK with adding another copy of equivalent files for the `autocxx_gen` tests, or programmatically writing files out from the test code.
